name: HealthGuard
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter: ^0.8.1
  intl: ^0.16.1
  syncfusion_flutter_datepicker: ^18.3.51-beta
  firebase_core: 0.5.0+1
  firebase_auth: 0.18.1+2
  # show images from internet
  cached_network_image: ^2.5.0
  image_picker: ^0.6.5
  progress_dialog: ^1.2.2
  cloud_firestore: 0.14.1+3
  firebase_storage: ^4.0.1
  json_annotation: 3.1.0
  # animated round slider or progress bar
  sleek_circular_slider: ^1.2.0+web
  # pedometer movement detection
  pedometer: ^2.0.2
  # manipulate format of datetime
  jiffy: ^3.0.1
  # small local data storage (only store none critical data)
  shared_preferences: ^0.5.12+4
  # Making http Requests
  http: ^0.12.2
  # Provides a webview widget
  webview_flutter: ^1.0.7
  # creating fuzzy timestamps
  timeago: ^2.0.29
  # Rendering QR code via a widget
  qr_flutter: ^3.2.0
  # Drawing SVG
  flutter_svg: ^0.19.2
  # Displaying local notifications
  flutter_local_notifications: ^4.0.1+1
  # Adding additional capabilities to Dart Streams and StreamControllers
  rxdart: ^0.24.0
  # Wrapper around Inherited Widget
  provider: ^4.3.3
  # The following adds the Cupertino Icons font to your application
  # Use with the CupertinoIcons class for iOS style icons
  cupertino_icons: ^1.0.0
  # Simplifies the task of updating app's launcher icon
  flutter_launcher_icons: ^0.8.1
  smart_select: ^4.3.2
  # Enable google sign in function in the app
  google_sign_in: ^4.5.9
  # Enabling the QR scanning Feature
  qrscan: ^0.2.22
  # request for permission to access a feature on the phone
  permission_handler: ^5.1.0+2
  # Use to select images from the Android and iOS image library
  image_gallery_saver: ^1.6.8
  # Provides a Google Maps widget
  google_maps_flutter: ^1.2.0
  # Dart Library for Google Maps Webservice
  google_maps_webservice: ^0.0.19
  # Provides easy access to platform specific location services
  geolocator: ^6.2.1
  # Launching URL in the mobile platform
  url_launcher: ^5.7.10
  # Customizable rating bar
  flutter_rating_bar: ^3.2.0+1
  location: ^3.2.4
  flutter_google_places: ^0.2.5

# Run flutter pub run flutter_launcher_icons:main after flutter pub get
flutter_icons:
  image_path: "assets/Logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: 1.10.4
  json_serializable: 3.5.0
  font_awesome_flutter: 8.10.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/Logo.png
    - assets/placeholder.jpg
    - assets/postImage.jpg
    - assets/user.png
    - assets/Hospital Suggestions.png
    - assets/Pedometer.png
    - assets/Medication Reminder.png
    - assets/Medical News Update.png
    - assets/Blood Pressure Diary.png
    - assets/Chat with Doctor.png
    - assets/E-Medical Report.png
    - assets/Patient Qr Scanner.png
    - assets/icons/logout.svg
    - assets/icons/medical-record.svg
    - assets/icons/personal-information.svg
    - assets/icons/help-center.svg
    - assets/capsule.png
    - assets/syringe.png
    - assets/medicalCategory/category1.png
    - assets/medicalCategory/category2.png
    - assets/medicalCategory/category3.png
    - assets/medicalCategory/category4.png
    - assets/medicalCategory/category5.png
    - assets/medicalCategory/category6.png
    - assets/medicalCategory/category7.png
    - assets/medicalCategory/category8.png
    - assets/docprofile/doc1.png
    - assets/docprofile/doc2.png
    - assets/docprofile/doc3.png
    - assets/docinfo/bg1.png
    - assets/icons/Walking.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
